## Splines & Curves Sandbox

In [12]:
import numpy as np

v = np.array([1, 2, 3])
v = np.append(v, 5)
v

array([1, 2, 3, 5])

In [16]:
c1, c2, c3 = np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])
np.invert(np.array([c1, c2, c3]).T)

array([[ -2,  -5,  -8],
       [ -3,  -6,  -9],
       [ -4,  -7, -10]])

In [18]:
np.array([[0, -1], [1, 0]]).dot([1, 1])

array([-1,  1])

In [22]:
focus = 30.
far_clip = 100.
cam_to_screen = np.array([[30, 0, 0, 0],
                          [0, 30, 0, 0],
                          [0, 0, -100/(-100+30), (-100*30)/(-100+30), 0],
                          [0, 0, 1, 0]])

/var/folders/n6/__4xwp6930gdgr6t72wmry8m0000gn/T/ipykernel_89721/2327359900.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  cam_to_screen = np.array([[30, 0, 0, 0],


In [23]:
np.array([1, 2]) * np.array([4, 5])

array([ 4, 10])

In [24]:
len(np.array([1, 1, 1]))

3

In [25]:
np.asarray((1, 2, 3))

array([1, 2, 3])